# Generated by Django 2.0.6 on 2018-06-05 16:02

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Milling'), (2, 'Turning')], default=1)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ('type__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ToolCooling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tool cooling',
                'verbose_name_plural': 'Tool coolings',
            },
        ),
        migrations.CreateModel(
            name='ToolEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Machine'), (2, 'Closet'), (3, 'NA')], default=1)),
                ('diameter', models.CharField(blank=True, max_length=10, null=True, verbose_name='Diameter')),
                ('angle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Angle')),
                ('cog_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cog count')),
                ('chip_flute_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chip flute')),
                ('pliers', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Pliers')),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Length')),
                ('radius', models.CharField(blank=True, max_length=20, null=True, verbose_name='Radius')),
                ('edge_radius', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Edge radius')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('geometry_x', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Geomentry X')),
                ('geometry_z', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Geomentry Z')),
                ('geometry_r', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Geomentry R')),
                ('geometry_y', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Geomentry Y')),
                ('geometry_c', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Geomentry C')),
                ('wear_x', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Wear X')),
                ('wear_z', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Wear Z')),
                ('wear_r', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Wear R')),
                ('wear_y', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Wear Y')),
                ('wear_c', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Wear C')),
                ('cooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toollist.ToolCooling', verbose_name='Cooling')),
            ],
            options={
                'verbose_name': 'Tool entry',
                'verbose_name_plural': 'Tools entries',
            },
        ),
        migrations.CreateModel(
            name='ToolHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toollist.Machine')),
            ],
            options={
                'verbose_name': 'Tool holder',
                'verbose_name_plural': 'Tool holders',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tool type',
                'verbose_name_plural': 'Tool types',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='toolentry',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toollist.ToolHolder', verbose_name='Holder'),
        ),
        migrations.AddField(
            model_name='toolentry',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toollist.Machine', verbose_name='Machine'),
        ),
        migrations.AddField(
            model_name='toolentry',
            name='tool',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='type', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, to='toollist.Tool', verbose_name='Tool'),
        ),
        migrations.AddField(
            model_name='toolentry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toollist.ToolType', verbose_name='Tool type'),
        ),
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toollist.ToolType', verbose_name='Tool type'),
        ),
        migrations.AlterUniqueTogether(
            name='toolentry',
            unique_together={('number', 'machine')},
        ),
    ]
