# Generated by Django 2.0.6 on 2018-06-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toollist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolentry',
            name='number',
            field=models.BigIntegerField(verbose_name='Number'),
        ),
    ]
