# Generated by Django 2.0.7 on 2018-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toollist', '0002_auto_20180610_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolentry',
            name='apm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Apm'),
        ),
    ]
