# Generated by Django 2.0.7 on 2018-07-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toollist', '0004_auto_20180708_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolentry',
            name='apm',
        ),
        migrations.AddField(
            model_name='toolentry',
            name='blade_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Blade length (Ap)'),
        ),
        migrations.AlterField(
            model_name='toolentry',
            name='chip_flute_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chip flute (Apm)'),
        ),
    ]
